baseURL = 'https://everett-escroc.github.io/bi-macro/'
languageCode = 'ko-kr'
title = 'bi-macro'
theme = "PaperMod"
paginate = 10

[params]
  description = "BI 엔지니어의 분석 리포트 연습"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  homeInfoParams = {Title = "bi-macro", Content = "BI 엔지니어의 분석 리포트 연습"}
  dateFormat = "2006년 01월 02일"

[menu]
  [[menu.main]]
    name = "글 목록"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "태그"
    url = "/tags/"
    weight = 2
